### ISSUE TITLE
difficulty 0 on S2 cgminer 4.9.1+

### ISSUE THREAD

**Issue by cytener2** [kanoi/cgminer-binaries#10]
When i trying pointing cgminer 4.9.1+ from AntS2 to stratehm proxy i got message like
Pool 0 set difficulty 0
as a result all hashpower rejected by pool

**Comment by kanoi** [comment]
Your issue provides no information - please post it on the forum with details
https://bitcointalk.org/index.php?topic=28402.0
Which Proxy? Which Pool? - and if it's an altcoin, don't bother posting.

**Comment by cytener2** [comment]
Oh sorry sir. When i using slush0-stratum-proxy all working fine. I think is only stratehm-mining-proxy issue.
