### ISSUE TITLE
AntS2 4.3.5s2 - Firmware applied, but will not save miner configuration changes

### ISSUE THREAD

**Issue by UdjatMiner** [kanoi/cgminer-binaries#4]
Hi,
I have been using the factory firmware on my S2 with P2Pool mining and it works fairly well after I changed the queue, scantime, and expiry.   I wanted to try your S2 build.  The firmware applied OK, but I have not been able to save my miner configuration.  It always reverts back to your miner configuration.  I am pretty sure I had "Keep settings:" ticked when I flashed the firmware, especially since it is ticked by default.

Thanks,
Scott

**Comment by kanoi** [comment]
Image updated to cgminer 4.9.1+
The probable cause of the config problem was that the Bitmain copy command to create a new config left the file protection as read only - I've added file protection changes in each place the config file is factory reset
