### ISSUE TITLE
Solo mining fix

### ISSUE THREAD

**Issue by FreeK** [kanoi/cgminer-binaries#8]
I use my Ant's just for solo mining and testing.
So right after the update to the latest cgminer binary, my farm went crazy beeping (even the neighbors cats noticed). There's a new cli flag in cgminer > 3.x when you're solo mining: --btc-address and you MUST set it, otherwise cgminer will refuse to mine.

I've cleaned up the default init script and fixed it: https://github.com/FreeK/cgminer-binaries/blob/master/AntS1/cgminer.init

Feel free to merge it into your own repo.

EDIT: you have to change the BTC address to your own ;)

Cheers,
Stephan

**Comment by kanoi** [comment]
The cgminer binary for the S1 is just cgminer - not the whole OS :)
